Repository marcosdosea/GestaoGrupoMusical, pull requests merged in 2023-09, with the labels that each got.

#480 Alterar Retornos de UC - Manter Grupo Musical
  Codigo/Core/Service/IGrupoMusicalService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/EventoController.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/FigurinoController.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/GrupoMusicalController.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/InstrumentoMusicalController.cs
  Codigo/Service/GrupoMusicalService.cs
Labels: enhancement, 6.0

#482 Alterar Retornos de UC - Movimentação Figurino
  Codigo/Core/Service/IMovimentacaoFigurinoService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/FigurinoController.cs
  Codigo/Service/MovimentacaoFigurinoService.cs
Labels: enhancement, 6.0

#475 Alterando o retorno para HttpStatusCode da UC-Pessoa
  Codigo/Core/Service/IPessoaService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/AdministradorGrupoMusicalController.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/BaseController.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/IdentityController.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/PessoaController.cs
  Codigo/Service/PessoaService.cs
Labels: 6.0

#485 Implementado get e post para o Associado enviar a justificava ausência de Ensaio
  Codigo/Core/DTO/EnsaioAssociadoDTO.cs
  Codigo/Core/Service/IEnsaioService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/EnsaioController.cs
  Codigo/GestaoGrupoMusicalWeb/Models/EnsaioJustificativaViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/EnsaiosAssociado.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/JustificarAusencia.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutAssociado.cshtml
  Codigo/Service/EnsaioService.cs
Labels: 6.0

#489 Atualizar consulta de regentes para lista de frequência de ensaio e details
  Codigo/Core/DTO/EnsaioDTO.cs
  Codigo/Core/DTO/EnsaioFrequenciaDTO.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/Details.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/RegistrarFrequencia.cshtml
  Codigo/Service/EnsaioService.cs
Labels: 6.0

#486 Alterar Retornos de UC - Movimentação Instrumento
  Codigo/Core/Service/IMovimentacaoInstrumentoService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/AdministradorGrupoMusicalController.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/EnsaioController.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/FigurinoController.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/GrupoMusicalController.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/IdentityController.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/InstrumentoMusicalController.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/PessoaController.cs
  Codigo/Service/MovimentacaoInstrumentoService.cs
Labels: enhancement, 6.0

#493 Alterar Retornos de UC - Manter Ensaio
  Codigo/Core/Service/IEnsaioService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/EnsaioController.cs
  Codigo/Service/EnsaioService.cs
Labels: enhancement, 6.0

#502 Adição de todas as Roles identity para Manter Figurino
  Codigo/GestaoGrupoMusicalWeb/Controllers/FigurinoController.cs
Labels: enhancement, 6.0

#500 Indentação, Remoção de namespace redundante e adição de roles
  Codigo/GestaoGrupoMusicalWeb/Controllers/FigurinoController.cs
Labels: enhancement, Fix, 6.0

#497 Atualizado o Edit de Ensaio
  Codigo/Core/Service/IEnsaioService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/EnsaioController.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/Edit.cshtml
  Codigo/GestaoGrupoMusicalWeb/wwwroot/js/autoComplete.js
  Codigo/Service/EnsaioService.cs
Labels: 6.0

#508 Tirando a paginação que estava implementada, e dependência do projeto
  Codigo/GestaoGrupoMusicalWeb/Controllers/FigurinoController.cs
  Codigo/GestaoGrupoMusicalWeb/GestaoGrupoMusicalWeb.csproj
  Codigo/GestaoGrupoMusicalWeb/Views/Figurino/_TabelaMovimentacao.cshtml
Labels: 6.0

#511 refactor: inserindo roles nas funções, instrumento musical controller
  Codigo/GestaoGrupoMusicalWeb/Controllers/InstrumentoMusicalController.cs
Labels: 6.0

#512 Adicionando Role Colaborador para poder manter um associado
  Codigo/GestaoGrupoMusicalWeb/Controllers/PessoaController.cs
Labels: 6.0

#504 Alterar retorno de Index Ensaio e voltar a exibir tela de início como do protótipo
  Codigo/GestaoGrupoMusicalWeb/Controllers/HomeController.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/Create.cshtml
Labels: 6.0

#515 refactor: comentando testes com erros
  Codigo/GestaoGrupoMusicalWebTests/Controllers/ColaboradorControllerTests.cs
  Codigo/GestaoGrupoMusicalWebTests/Controllers/EnsaioControllerTests.cs
  Codigo/GestaoGrupoMusicalWebTests/Controllers/EventoControllerTests.cs
  Codigo/GestaoGrupoMusicalWebTests/Controllers/GrupoMusicalControllerTests.cs
  Codigo/GestaoGrupoMusicalWebTests/Controllers/InstrumentoMusicalControllerTests.cs
  Codigo/GestaoGrupoMusicalWebTests/Controllers/PessoaControllerTests.cs
  Codigo/ServiceTests/EnsaioServiceTests.cs
  Codigo/ServiceTests/EventoServiceTests.cs
  Codigo/ServiceTests/GrupoMusicalServiceTests.cs
Labels: refactor, 6.0

#513 Implementado menu "Meus Dados" para o usuário poder ver/editar suas infos
  Codigo/Core/DTO/UserDTO.cs
  Codigo/Core/Service/IPessoaService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/IdentityController.cs
  Codigo/GestaoGrupoMusicalWeb/Helpers/ApplicationUserClaims.cs
  Codigo/GestaoGrupoMusicalWeb/Mapper/UserProfile.cs
  Codigo/GestaoGrupoMusicalWeb/Models/UserSystemViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Models/UserViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Identity/Perfil.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Identity/PerfilSistema.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutAdmSistema.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutAssociado.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutColaborador.cshtml
  Codigo/GestaoGrupoMusicalWeb/wwwroot/js/site.js
  Codigo/Service/PessoaService.cs
Labels: 6.0

#517 Correção da localização da mensagem, quando não tem empréstimo ou devolução.
  Codigo/GestaoGrupoMusicalWeb/Views/Figurino/_TabelaDevolucaoFigurino.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Figurino/_TabelaFigurinoEntregue.cshtml
Labels: 6.0

#487 Descartar Figurino - Funcionalidade - Movimentar Figurino
  Codigo/Core/Service/IMovimentacaoFigurinoService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/FigurinoController.cs
  Codigo/GestaoGrupoMusicalWeb/Models/MovimentacaoFigurinoViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Figurino/Movimentar.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Figurino/_TabelaMovimentacao.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutColaborador.cshtml
  Codigo/GestaoGrupoMusicalWeb/wwwroot/js/Figurino/Movimentar.js
  Codigo/Service/EnsaioService.cs
  Codigo/Service/MovimentacaoFigurinoService.cs
Labels: 6.0
