Repository marcosdosea/GestaoGrupoMusical, pull requests merged in 2023-07, with the labels that each got.

#154 Refatorando selectlist da classe pessoa
  Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Create.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Edit.cshtml
Labels: refactor, 2.0

#138 Método para adicionar data de saída, tirar o ativo e por o motivo para a saída do associado
  Codigo/Core/Service/IPessoaService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/PessoaController.cs
  Codigo/GestaoGrupoMusicalWeb/GestaoGrupoMusicalWeb.csproj
  Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Index.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/RemoveAssociado.cshtml
  Codigo/Service/PessoaService.cs
Labels: 1.5

#156 Adicionando mascaras nas views de grupoMusical
  Codigo/GestaoGrupoMusicalWeb/Controllers/GrupoMusicalController.cs
  Codigo/GestaoGrupoMusicalWeb/Models/GrupoMusicalViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Views/GrupoMusical/Create.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/GrupoMusical/Edit.cshtml
Labels: refactor, feat

#160 Notificações de Sucesso/Alerta e Erro para Movimentação de Instrumento
  Codigo/Core/Service/IMovimentacaoInstrumentoService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/BaseController.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/InstrumentoMusicalController.cs
  Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/Movimentar.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Shared/_Notificar.cshtml
  Codigo/Service/MovimentacaoInstrumentoService.cs
Labels: 2.0

#159 Implementação do UC_manter informativo
  Codigo/Core/DTO/InformativoDTO.cs
  Codigo/Core/Service/IInformativoService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/HomeController.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/InformativoController.cs
  Codigo/GestaoGrupoMusicalWeb/Mapper/InformativoProfile.cs
  Codigo/GestaoGrupoMusicalWeb/Mapper/InformativoProfileDTO.cs
  Codigo/GestaoGrupoMusicalWeb/Models/InformativoViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Models/InformativoViewModelDTO.cs
  Codigo/GestaoGrupoMusicalWeb/Models/TelaPrincipalViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Program.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Home/Index.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Informativo/Create.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Informativo/Delete.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Informativo/Details.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Informativo/Edit.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Informativo/Index.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutColaborador.cshtml
  Codigo/Service/InformativoService.cs
Labels: enhancement, 1.5

#141 Remoção do campo "Status" da tela de edição de instrumento musical
  Codigo/GestaoGrupoMusicalWeb/Controllers/InstrumentoMusicalController.cs
  Codigo/GestaoGrupoMusicalWeb/Models/InstrumentoMusicalViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/Edit.cshtml
Labels: 2.0

#165 Feita a implementação da unidade de teste do "ColaboradorControllerTest"
  Codigo/GestaoGrupoMusicalWebTests/Controllers/ColaboradorControllerTests.cs
Labels: 2.0

#167 Adição de rotas da Home/index
  Codigo/GestaoGrupoMusicalWeb/Views/Home/Index.cshtml
  Codigo/Service/EnsaioService.cs
  Codigo/Service/EventoService.cs
  Codigo/Service/InformativoService.cs
Labels: enhancement

#170 Finalizado a estilização da tela de Ensaio
  Codigo/Core/DTO/EnsaioIndexDTO.cs
  Codigo/Core/Service/IEnsaioService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/EnsaioController.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/Create.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/Delete.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/Details.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/Edit.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/Index.cshtml
  Codigo/Service/EnsaioService.cs
Labels: refactor, feat

#176 refactor: alterando a responsividade da tabela de enssaio
  Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/Index.cshtml
Labels: refactor, 2.0

#172 Projeto Util criado e classe CPFAttribute criada e implementada
  Codigo/GestaoGrupoMusical.sln
  Codigo/GestaoGrupoMusicalWeb/Controllers/PessoaController.cs
  Codigo/GestaoGrupoMusicalWeb/GestaoGrupoMusicalWeb.csproj
  Codigo/GestaoGrupoMusicalWeb/Models/PessoaViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/RemoveAssociado.cshtml
  Codigo/Service/PessoaService.cs
  Codigo/Util/CPFAttribute.cs
  Codigo/Util/Methods.cs
  Codigo/Util/Util.csproj
Labels: 2.0

#181 Estilização da lista de associados
  Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Index.cshtml
Labels: enhancement, 1.5

#184 Adição de método para validar o CPF quando for Editar a Pessoa
  Codigo/Core/Service/IPessoaService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/PessoaController.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Index.cshtml
  Codigo/Service/PessoaService.cs
Labels: 2.0

#177 Adicionado cadastro identity, envio de e-mail e estilo para Administrador Grupo
  Codigo/Core/Service/IPessoaService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/AdministradorGrupoMusicalController.cs
  Codigo/GestaoGrupoMusicalWeb/Models/AdministradorGrupoMusicalViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Views/AdministradorGrupoMusical/Create.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/AdministradorGrupoMusical/Delete.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/AdministradorGrupoMusical/Index.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/AdministradorGrupoMusical/_Create.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/AdministradorGrupoMusical/_TabelaAdministrador.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/GrupoMusical/Index.cshtml
  Codigo/GestaoGrupoMusicalWeb/wwwroot/css/site.css
  Codigo/Service/PessoaService.cs
Labels: 2.0

#187 Estilização da tela index de evento
  Codigo/Core/DTO/EventoIndexDTO.cs
  Codigo/Core/Service/IEventoService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/EventoController.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Evento/Index.cshtml
  Codigo/Service/EventoService.cs
Labels: refactor, feat, 2.0

#178 Tela_Index-Instrumento_Musical
  Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/Index.cshtml
Labels: 1.5

#190 Tela de Login de Acordo Com Protótipos
  Codigo/GestaoGrupoMusicalWeb/Views/Identity/Autenticar.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutLogin.cshtml
  Codigo/GestaoGrupoMusicalWeb/wwwroot/assets/imagem de bem vindo.png
  Codigo/GestaoGrupoMusicalWeb/wwwroot/assets/logo_batalase_SF.png
  Codigo/GestaoGrupoMusicalWeb/wwwroot/css/headerLayout.css
  Codigo/GestaoGrupoMusicalWeb/wwwroot/css/site.css
Labels: enhancement, 2.0

#192 Tela index do Grupo Musical finalizada
  Codigo/GestaoGrupoMusicalWeb/Views/GrupoMusical/Index.cshtml
Labels: 2.0

#199 Notificações tela de adicionar associado
  Codigo/Core/Service/IPessoaService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/PessoaController.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Create.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Index.cshtml
  Codigo/Service/PessoaService.cs
Labels: refactor, feat, 3.0

#186 Estilização de cadastro do associado
  Codigo/GestaoGrupoMusicalWeb/Models/PessoaViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Create.cshtml
  Codigo/GestaoGrupoMusicalWeb/wwwroot/css/site.css
Labels: enhancement, 2.0

#198 Notificações - Edit - UC-Manter Grupo Musical
  Codigo/GestaoGrupoMusicalWeb/Controllers/GrupoMusicalController.cs
  Codigo/GestaoGrupoMusicalWeb/Models/GrupoMusicalViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Views/GrupoMusical/Index.cshtml
Labels: 2.0

#204 Estilização da view edit do associado
  Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Edit.cshtml
Labels: 3.0

#202 Notificações para o create de instrumentoMusical
  Codigo/GestaoGrupoMusicalWeb/Controllers/InstrumentoMusicalController.cs
  Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/Create.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/Index.cshtml
  Codigo/Service/InstrumentoMusicalService.cs
Labels: 3.0

#208 Alinhado o cabecalho da tabela de eventos
  Codigo/GestaoGrupoMusicalWeb/Models/PessoaViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Evento/Index.cshtml
Labels: refactor, 3.0

#212 Remover Input Select Colaborador de Movimento Instrumento E adicionar notificações restantes
  Codigo/Core/Service/IMovimentacaoInstrumentoService.cs
  Codigo/Core/Service/IPessoaService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/InstrumentoMusicalController.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/PessoaController.cs
  Codigo/GestaoGrupoMusicalWeb/Models/MovimentacaoInstrumentoViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/Index.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/Movimentar.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/_TabelaMovimentacao.cshtml
  Codigo/GestaoGrupoMusicalWeb/wwwroot/css/site.css
  Codigo/Service/InstrumentoMusicalService.cs
  Codigo/Service/MovimentacaoInstrumentoService.cs
  Codigo/Service/PessoaService.cs
Labels: 3.0

#218 Refatoração do script de mascara de javascript
  Codigo/GestaoGrupoMusicalWeb/Models/AdministradorGrupoMusicalViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Views/AdministradorGrupoMusical/_Create.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/GrupoMusical/Create.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/GrupoMusical/Edit.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Identity/Autenticar.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Identity/Cadastrar.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Create.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Edit.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutAdmSistema.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutColaborador.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutLogin.cshtml
  Codigo/GestaoGrupoMusicalWeb/wwwroot/js/Mascara.js
Labels: refactor, feat, 3.0

#219 Adicionado notificação de delete em associado
  Codigo/Core/Service/IPessoaService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/PessoaController.cs
  Codigo/Service/PessoaService.cs
Labels: refactor, feat, 3.0

#224 Criação da recursividade para o cadastro do associado
  Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Create.cshtml
Labels: enhancement, 2.0

#214 UC-Manter Instrumento Musical - Notificação - view Edit e Delete
  Codigo/GestaoGrupoMusicalWeb/Controllers/InstrumentoMusicalController.cs
  Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/Edit.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/Index.cshtml
Labels: 3.0

#232 Busca cep adicionado ao associado
  Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Create.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Edit.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutColaborador.cshtml
  Codigo/GestaoGrupoMusicalWeb/wwwroot/js/BuscaCep.js
Labels: feat, 3.0

#240 Adição de mensagem de erro para o campo Estado de grupoMusical
  Codigo/GestaoGrupoMusicalWeb/Models/GrupoMusicalViewModel.cs
Labels: enhancement, 2.0

#243 Estilização do cadastro e edição das view de grupo musical
  Codigo/GestaoGrupoMusicalWeb/Views/GrupoMusical/Create.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/GrupoMusical/Edit.cshtml
Labels: enhancement, 2.0

#249 Adição das validações stringLength e placeholder para grupoMusical
  Codigo/GestaoGrupoMusicalWeb/Models/GrupoMusicalViewModel.cs
Labels: enhancement, 2.0

#241 Criada funcionalidade para enviar email de redefinição de senha ao criar/add um adm de grupo musical
  Codigo/GestaoGrupoMusicalWeb/Controllers/IdentityController.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/PessoaController.cs
  Codigo/GestaoGrupoMusicalWeb/Models/IdentityViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Program.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Identity/Autenticar.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Identity/ForgotPassword.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Identity/PasswordChanged.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Identity/ResetPassword.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutLogin.cshtml
  Codigo/GestaoGrupoMusicalWeb/wwwroot/css/site.css
  Codigo/GestaoGrupoMusicalWeb/wwwroot/js/site.js
  Codigo/Service/PessoaService.cs
Labels: enhancement, refactor, Fix, 3.0

#226 Adicionado cadastro identity para Associado e Layout Associado
  Codigo/Core/Service/IPessoaService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/AdministradorGrupoMusicalController.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/HomeController.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/IdentityController.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/InstrumentoMusicalController.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/PessoaController.cs
  Codigo/GestaoGrupoMusicalWeb/Models/PessoaViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Colaborador/Create.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Colaborador/Delete.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/Movimentacoes.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Create.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Delete.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Details.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Edit.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Index.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutAssociado.cshtml
  Codigo/Service/PessoaService.cs
Labels: 3.0

#254 Refatoração do metodo que cria token para redefinição de senha
  Codigo/GestaoGrupoMusicalWeb/Controllers/AdministradorGrupoMusicalController.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/BaseController.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/IdentityController.cs
  Codigo/GestaoGrupoMusicalWeb/Views/AdministradorGrupoMusical/Index.cshtml
Labels: refactor, 3.0

#253 Fazer validação com select list usando dictonary para tipo de chave pix em grupo musical
  Codigo/GestaoGrupoMusicalWeb/Controllers/GrupoMusicalController.cs
  Codigo/GestaoGrupoMusicalWeb/Models/GrupoMusicalViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Views/GrupoMusical/Create.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/GrupoMusical/Edit.cshtml
Labels: enhancement, 3.0

#256 Remoção do campo IdGrupoMusical da tela Create de Evento
  Codigo/Core/Service/IGrupoMusicalService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/EventoController.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Evento/Create.cshtml
  Codigo/Service/GrupoMusicalService.cs
Labels: 3.0

#259 Mudança do modo de exibição da data exibindo sem a hora
  Codigo/GestaoGrupoMusicalWeb/Controllers/InstrumentoMusicalController.cs
Labels: refactor, 3.0

#257 Adicionado notificação para cadastro de adm grupo musical
  Codigo/Core/Service/IPessoaService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/AdministradorGrupoMusicalController.cs
  Codigo/GestaoGrupoMusicalWeb/Views/AdministradorGrupoMusical/Index.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/AdministradorGrupoMusical/_Create.cshtml
  Codigo/Service/PessoaService.cs
Labels: refactor, feat, 3.0

#263 Estilização da view Edit de instrumento musical
  Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/Edit.cshtml
Labels: enhancement, 3.0

#261 Adição das notificações para editar um instrumento musical.
  Codigo/Core/Service/IInstrumentoMusicalService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/InstrumentoMusicalController.cs
  Codigo/Service/InstrumentoMusicalService.cs
Labels: enhancement, 3.0

#276 Criado metodo que retorna lista com todos os associados de um mesmo Grupo Musical
  Codigo/Core/Service/IPessoaService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/PessoaController.cs
  Codigo/Service/PessoaService.cs
Labels: enhancement, 3.0

#279 Correção de erro que impedia execução completa do método
  Codigo/GestaoGrupoMusicalWeb/Controllers/AdministradorGrupoMusicalController.cs
Labels: Fix, 3.0

#277 Details grupo musical
  Codigo/GestaoGrupoMusicalWeb/Views/GrupoMusical/Details.cshtml
Labels: 3.0

#285 Subindo validação para verificar o tipo de mascara que será atribuido ao valor selecionado no Select de "ChavetipoPix"
  Codigo/GestaoGrupoMusicalWeb/Models/GrupoMusicalViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Views/GrupoMusical/Create.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/GrupoMusical/Edit.cshtml
  Codigo/GestaoGrupoMusicalWeb/wwwroot/js/Mascara.js
Labels: 3.0

#291 Ocultando o que será entregue na primeira release resolve #290
  Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutColaborador.cshtml
Labels: 3.0

#295 Criado um template para Pull Request
  .github/pull_request_template.md
Labels: enhancement, 3.0

#287 Tela excluir grupo musical finalizada
  Codigo/GestaoGrupoMusicalWeb/Views/GrupoMusical/Delete.cshtml
Labels: enhancement, 3.0

#289 Consertando a view edit de grupo Musical
  Codigo/GestaoGrupoMusicalWeb/Views/GrupoMusical/Details.cshtml
Labels: enhancement, 3.0

#297 Update ultima linha pull_request_template.md
  .github/pull_request_template.md
Labels: enhancement, 3.0

#270 Remoção dos botões "Novo..." da homepage
  Codigo/GestaoGrupoMusicalWeb/Controllers/HomeController.cs
Labels: 3.0

#283 Adicionado confirmar empréstimo/devolução de instrumento para Associado
  Codigo/Core/DTO/InstrumentoAssociadoDTO.cs
  Codigo/Core/Service/IMovimentacaoInstrumentoService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/InstrumentoMusicalController.cs
  Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/Movimentacoes.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/_TabelaDevolucoesAssociado.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/_TabelaEmprestimosAssociado.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutAssociado.cshtml
  Codigo/GestaoGrupoMusicalWeb/wwwroot/js/modal.js
  Codigo/Service/MovimentacaoInstrumentoService.cs
Labels: 3.0

#300 Feita restrição de associado e ordenação em ordem alfabética
  Codigo/Core/Service/IPessoaService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/InstrumentoMusicalController.cs
  Codigo/Service/PessoaService.cs
Labels: 3.0

#307 Resolvido bug de Edit associado
  Codigo/GestaoGrupoMusicalWeb/Controllers/PessoaController.cs
  Codigo/Service/PessoaService.cs
Labels: 4.0

#305 Adicionado nome de usuário logado ao Layout
  Codigo/Core/DTO/UserDTO.cs
  Codigo/Core/Service/IPessoaService.cs
  Codigo/GestaoGrupoMusicalWeb/Helpers/ApplicationUserClaims.cs
  Codigo/GestaoGrupoMusicalWeb/Program.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutAdmSistema.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutAssociado.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutColaborador.cshtml
  Codigo/Service/PessoaService.cs
Labels: 4.0

#296 Definido envio de email para redefinição de senha apenas para novo usuário
  Codigo/Core/Service/IPessoaService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/AdministradorGrupoMusicalController.cs
  Codigo/Service/PessoaService.cs
Labels: enhancement, Fix, 3.0, 4.0

#311 Criado método para gerar senha aleatória para user identity
  Codigo/Core/Service/IPessoaService.cs
  Codigo/Service/PessoaService.cs
Labels: enhancement, 4.0

#309 Adicionar input type hidden no campo CNPJ na view delete de Grupo Musical, Corrigir mensagem de erro de exclusão de grupo musical.
  Codigo/GestaoGrupoMusicalWeb/Controllers/GrupoMusicalController.cs
  Codigo/GestaoGrupoMusicalWeb/Views/GrupoMusical/Delete.cshtml
Labels: enhancement, 4.0

#304 Criado body padrão para envio de email
  Codigo/Core/Service/IPessoaService.cs
  Codigo/Email/Email.csproj
  Codigo/Email/EmailModel.cs
  Codigo/Email/EmailService.cs
  Codigo/Email/Template/EmailResource.Designer.cs
  Codigo/Email/Template/EmailResource.resx
  Codigo/GestaoGrupoMusicalWeb/Controllers/AdministradorGrupoMusicalController.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/BaseController.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/IdentityController.cs
  Codigo/Service/PessoaService.cs
Labels: enhancement, refactor, 3.0, 4.0

#314 Add role Associado para ConfirmarMovimentacao
  Codigo/GestaoGrupoMusicalWeb/Controllers/InstrumentoMusicalController.cs
Labels: 4.0

#318 refactor: tirando o justify, alinhando os itens
  Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/Index.cshtml
Labels: refactor, 4.0

#322 Adicionando notificacoes de alerta no autenticar
  Codigo/GestaoGrupoMusicalWeb/Controllers/IdentityController.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Identity/Autenticar.cshtml
Labels: refactor, feat, 4.0

#325 Adicionado notificações ao deletar instrumento
  Codigo/Core/Service/IInstrumentoMusicalService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/InstrumentoMusicalController.cs
  Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/Delete.cshtml
  Codigo/Service/InstrumentoMusicalService.cs
Labels: 4.0

#329 Alinhamento de botões - Index - Grupo Musical
  Codigo/GestaoGrupoMusicalWeb/Views/GrupoMusical/Index.cshtml
Labels: 4.0

#328 Correção de bug ao adicionar um adm de grupo que já era associado
  Codigo/GestaoGrupoMusicalWeb/Controllers/HomeController.cs
  Codigo/Service/PessoaService.cs
Labels: Fix, 4.0

#292 Tela de Instrumentos Musicais - Delete
  Codigo/Core/DTO/InstrumentoMusicalDTO.cs
  Codigo/Core/Service/IInstrumentoMusicalService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/InstrumentoMusicalController.cs
  Codigo/GestaoGrupoMusicalWeb/Models/InstrumentoMusicalViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/Delete.cshtml
  Codigo/Service/InstrumentoMusicalService.cs
Labels: 3.0

#320 Ajustes na view Details - UC Grupo Musical
  Codigo/GestaoGrupoMusicalWeb/Views/GrupoMusical/Details.cshtml
Labels: 4.0

#336 Tornando email unico no identity e validando no código
  Codigo/Core/Service/IPessoaService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/AdministradorGrupoMusicalController.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/PessoaController.cs
  Codigo/GestaoGrupoMusicalWeb/Program.cs
  Codigo/Service/PessoaService.cs
Labels: enhancement, refactor, 4.0

#319 Validação de CPF para views de grupo musical.
  Codigo/GestaoGrupoMusicalWeb/Views/GrupoMusical/Create.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/GrupoMusical/Edit.cshtml
  Codigo/GestaoGrupoMusicalWeb/wwwroot/js/Mascara.js
Labels: enhancement, 4.0

#333 Adicionado uso do modal para Excluir e Notificar movimentação e Restringir envio de e-mail
  Codigo/Core/Service/IMovimentacaoInstrumentoService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/InstrumentoMusicalController.cs
  Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/_TabelaMovimentacao.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutColaborador.cshtml
  Codigo/Service/MovimentacaoInstrumentoService.cs
Labels: 4.0

#339 Enviando email para redefinir senha do associado. #337
  Codigo/GestaoGrupoMusicalWeb/Controllers/PessoaController.cs
Labels: enhancement, Fix, 4.0

#340 Proibir associado com status ativo=não de autenticar
  Codigo/Core/DTO/UserDTO.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/HomeController.cs
  Codigo/GestaoGrupoMusicalWeb/Helpers/ApplicationUserClaims.cs
  Codigo/Service/PessoaService.cs
Labels: 4.0

#335 Adicionando Modal para excluir e notificar da view index de administrador de grupo musical. resolve #323
  Codigo/GestaoGrupoMusicalWeb/Views/AdministradorGrupoMusical/_TabelaAdministrador.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutAdmSistema.cshtml
  Codigo/Service/PessoaService.cs
Labels: enhancement, 4.0

#344 Alterar Status Ativo de Associado Ao Alterar Senha e Resolvido Bug com Login ADM Sistema
  Codigo/Core/Service/IPessoaService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/HomeController.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/IdentityController.cs
  Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/Index.cshtml
  Codigo/Service/PessoaService.cs
Labels: enhancement, Fix, 4.0

#346 Correção ao ativar associado. #345
  Codigo/Service/PessoaService.cs
Labels: Fix, 4.0
