Repository marcosdosea/GestaoGrupoMusical, pull requests merged in 2023-08, with the labels that each got.

#348 Implementado UC - Manter Figurino
  Codigo/Core/Service/IFigurinoService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/FigurinoController.cs
  Codigo/GestaoGrupoMusicalWeb/Mapper/FigurinoProfile.cs
  Codigo/GestaoGrupoMusicalWeb/Models/FigurinoViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Program.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Figurino/Create.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Figurino/Delete.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Figurino/Edit.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Figurino/Index.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutColaborador.cshtml
  Codigo/Service/FigurinoService.cs
Labels: enhancement, 4.0

#351 Aplicação do design system da view details de grupo musical.
  Codigo/GestaoGrupoMusicalWeb/Views/GrupoMusical/Details.cshtml
  Codigo/GestaoGrupoMusicalWeb/wwwroot/css/site.css
Labels: 4.0

#358 Testes de Unidade - Movimentação de Instrumento - Service
  Codigo/Service/MovimentacaoInstrumentoService.cs
  Codigo/ServiceTests/MovimentacaoInstrumentoServiceTest.cs
  Codigo/ServiceTests/PessoaServiceTests.cs
Labels: 4.0

#353 Adicionar o design system a view de cadastro de figurino
  Codigo/GestaoGrupoMusicalWeb/Views/Figurino/Create.cshtml
Labels: enhancement, 4.0

#355 Estilização da view edit de figurino.
  Codigo/GestaoGrupoMusicalWeb/Views/Figurino/Edit.cshtml
Labels: enhancement, 4.0

#357 Adição de modal para excluir figurino.
  Codigo/GestaoGrupoMusicalWeb/Views/Figurino/Index.cshtml
Labels: enhancement, 4.0

#365 Aplicar Design System view Create de ensaio
  Codigo/GestaoGrupoMusicalWeb/Models/EnsaioViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/Create.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutColaborador.cshtml
Labels: enhancement, 4.0

#369 Removendo redirecionar
  Codigo/GestaoGrupoMusicalWeb/Controllers/AdministradorGrupoMusicalController.cs
  Codigo/GestaoGrupoMusicalWeb/Views/AdministradorGrupoMusical/Index.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/AdministradorGrupoMusical/_Create.cshtml
Labels: refactor, 4.0

#373 Atualizar Create e Edit de Ensaio seguindo o Protótipo de Baixa Fidelidade
  Codigo/GestaoGrupoMusicalWeb/Controllers/EnsaioController.cs
  Codigo/GestaoGrupoMusicalWeb/Helpers/ApplicationUserClaims.cs
  Codigo/GestaoGrupoMusicalWeb/Models/EnsaioViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/Create.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/Delete.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/Details.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/Edit.cshtml
  Codigo/Service/EnsaioService.cs
Labels: 4.0

#376 Feita a estilização da index de informativo
  Codigo/GestaoGrupoMusicalWeb/Views/Informativo/Index.cshtml
Labels: 4.0

#370 Criação do estoque de figurino
  Codigo/Core/DTO/EstoqueDTO.cs
  Codigo/Core/Service/IFigurinoService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/FigurinoController.cs
  Codigo/GestaoGrupoMusicalWeb/Mapper/EstoqueDTOProfile.cs
  Codigo/GestaoGrupoMusicalWeb/Models/EstoqueDTOViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Figurino/Estoque.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Figurino/Index.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Figurino/_TabelaEstoque.cshtml
  Codigo/Service/FigurinoService.cs
Labels: enhancement, 4.0

#368 Removi os DTO de informativo, já que estava com os mesmos campos do mesmo
  Codigo/Core/DTO/InformativoDTO.cs
  Codigo/Core/Service/IInformativoService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/HomeController.cs
  Codigo/GestaoGrupoMusicalWeb/Mapper/InformativoProfileDTO.cs
  Codigo/GestaoGrupoMusicalWeb/Models/InformativoViewModelDTO.cs
  Codigo/GestaoGrupoMusicalWeb/Models/TelaPrincipalViewModel.cs
  Codigo/Service/InformativoService.cs
Labels: 4.0

#380 Adição de modal para excluir ensaio
  Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/Delete.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/Index.cshtml
Labels: feat, 5.0

#379 Movimentar Figurino
  Codigo/Core/DTO/MovimentacaoFigurinoDTO.cs
  Codigo/Core/Service/IMovimentacaoFigurinoService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/FigurinoController.cs
  Codigo/GestaoGrupoMusicalWeb/Models/MovimentacaoFigurinoViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Program.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Figurino/Movimentar.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Figurino/_TabelaMovimentacao.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/GrupoMusical/Details.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutAdmSistema.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutAssociado.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutColaborador.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutLogin.cshtml
  Codigo/GestaoGrupoMusicalWeb/wwwroot/css/site.css
  Codigo/Service/MovimentacaoFigurinoService.cs
  Codigo/Service/MovimentacaoInstrumentoService.cs
Labels: enhancement, 5.0

#388 Restante da solução da PR #379
  Codigo/GestaoGrupoMusicalWeb/Controllers/FigurinoController.cs
Labels: Fix, 5.0

#371 Edit - UC Manter Ensaio - Design System
  Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/Edit.cshtml
Labels: 4.0

#389 Create para Estoque de Figurino
  Codigo/Core/Service/IFigurinoService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/FigurinoController.cs
  Codigo/GestaoGrupoMusicalWeb/Mapper/EstoqueDTOProfile.cs
  Codigo/GestaoGrupoMusicalWeb/Models/EstoqueDTOViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Models/EstoqueViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Figurino/CreateEstoque.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Figurino/Estoque.cshtml
  Codigo/Service/FigurinoService.cs
Labels: enhancement, feat, 5.0

#397 Adicionando o modal para o instrumento musical
  Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/Delete.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/Index.cshtml
Labels: 5.0

#403 Implementação de confirmar movimentação
  Codigo/Core/DTO/MovimentacaoAssociadoFigurinoDTO.cs
  Codigo/Core/Service/IMovimentacaoFigurinoService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/FigurinoController.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Figurino/Movimentacoes.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Figurino/_TabelaDevolucaoFigurino.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Figurino/_TabelaFigurinoEntregue.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutAssociado.cshtml
  Codigo/Service/MovimentacaoFigurinoService.cs
Labels: refactor, feat, 5.0

#405 Index - Figurinos - Design System
  Codigo/GestaoGrupoMusicalWeb/Views/Figurino/Index.cshtml
Labels: 5.0

#406 Implementação do EditEstoque
  Codigo/Core/Service/IFigurinoService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/FigurinoController.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Figurino/EditEstoque.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Figurino/_TabelaEstoque.cshtml
  Codigo/Service/FigurinoService.cs
Labels: enhancement, 2.0, 5.0

#413 Alteração feita para o campo type read-only e disabled juntamente com a mudança do cursor.
  Codigo/GestaoGrupoMusicalWeb/wwwroot/css/site.css
Labels: enhancement, 5.0

#415 Mudança na rota de Ensaio, Evento e Informativo, todas rotas da views create referente ao botão voltar para Home/index
  Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/Create.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Evento/Create.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Informativo/Create.cshtml
Labels: enhancement, 5.0

#395 Details - Design System - Ensaio
  Codigo/Core/DTO/EnsaioDTO.cs
  Codigo/Core/Service/IEnsaioService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/EnsaioController.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/Details.cshtml
  Codigo/Service/EnsaioService.cs
Labels: 5.0

#417 Adicionado design system a tela de movimentações do associado
  Codigo/Core/DTO/MovimentacaoAssociadoFigurinoDTO.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Figurino/_TabelaDevolucaoFigurino.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Figurino/_TabelaFigurinoEntregue.cshtml
Labels: refactor, 5.0

#421 Implementação de Frequência de Ensaio
  Codigo/Core/DTO/EnsaioFrequenciaDTO.cs
  Codigo/Core/Service/IEnsaioService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/EnsaioController.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/Index.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/RegistrarFrequencia.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/_TabelaFrequencia.cshtml
  Codigo/Service/EnsaioService.cs
Labels: 5.0

#423 Estilizado view novo estoque
  Codigo/GestaoGrupoMusicalWeb/Views/Figurino/CreateEstoque.cshtml
Labels: 5.0

#420 Alteração de SelecctList para label para associado que já tenha movimentação com um instrumento
  Codigo/GestaoGrupoMusicalWeb/Controllers/InstrumentoMusicalController.cs
  Codigo/GestaoGrupoMusicalWeb/Models/MovimentacaoInstrumentoViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/Movimentar.cshtml
Labels: 5.0

#401 Delete Estoque - Figurino
  Codigo/Core/Service/IFigurinoService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/FigurinoController.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Figurino/_TabelaEstoque.cshtml
  Codigo/Service/FigurinoService.cs
Labels: 5.0

#428 Estilizado view edit estoque.
  Codigo/GestaoGrupoMusicalWeb/Views/Figurino/EditEstoque.cshtml
Labels: 5.0

#425 [Bug] No select list para "Tamanho de Roupa" no cadastro de associado
  Codigo/GestaoGrupoMusicalWeb/Controllers/PessoaController.cs
Labels: bug, refactor, 5.0

#429 Teste de Unidade - MovimentacaoFigurino - Service
  Codigo/ServiceTests/MovimentacaoFigurinoServiceTests.cs
Labels: test, 5.0

#431 Removida opção de danificado ao movimentar figurino
  Codigo/GestaoGrupoMusicalWeb/Controllers/FigurinoController.cs
  Codigo/GestaoGrupoMusicalWeb/Models/MovimentacaoFigurinoViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Figurino/Movimentar.cshtml
  Codigo/Service/MovimentacaoFigurinoService.cs
Labels: Fix, 5.0

#434 Restrição para que somente o administrador do grupo possa acessar os instrumento do grupo
  Codigo/GestaoGrupoMusicalWeb/Controllers/InstrumentoMusicalController.cs
Labels: 5.0

#441 Feito o scaffolding da atualização do banco
  Codigo/Core/Ensaio.cs
  Codigo/Core/Ensaiopessoa.cs
  Codigo/Core/Evento.cs
  Codigo/Core/Eventopessoa.cs
  Codigo/Core/Figurinomanequim.cs
  Codigo/Core/GrupoMusicalContext.cs
  Codigo/Core/Movimentacaofigurino.cs
  Codigo/Core/Papelgrupo.cs
  Codigo/Core/Pessoa.cs
Labels: refactor, 5.0

#444 Verificação para identificar, se os ensaio estão retornando para pessoa do grupo musical correto
  Codigo/Core/DTO/EnsaioDTO.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/EnsaioController.cs
  Codigo/Service/EnsaioService.cs
Labels: feat, 5.0

#445 Teste de Unidade - Service - Figurino
  Codigo/Service/FigurinoService.cs
  Codigo/ServiceTests/FigurinoServiceTests.cs
Labels: 5.0, 6.0

#452 refactor: adicionando rotar para o botão de edit estoque. #451
  Codigo/GestaoGrupoMusicalWeb/Views/Figurino/_TabelaEstoque.cshtml
Labels: 5.0

#458 Adicionado Novo Atributo Ao Estoque
  Codigo/Core/DTO/EstoqueDTO.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/FigurinoController.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Figurino/Estoque.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Figurino/_TabelaEstoque.cshtml
Labels: enhancement, 6.0

#456 Alterado Tipo de Retorno dos Métodos de UC - Manter Figurino
  Codigo/Core/Service/IFigurinoService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/FigurinoController.cs
  Codigo/Service/FigurinoService.cs
Labels: enhancement, 6.0

#465 Atualizar cadastro de Ensaio
  Codigo/Core/DTO/EnsaioDTO.cs
  Codigo/Core/Service/IEnsaioService.cs
  Codigo/Core/Service/IPessoaService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/EnsaioController.cs
  Codigo/GestaoGrupoMusicalWeb/Models/EnsaioViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/Create.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/Edit.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Shared/_AutoCompleteCssPartial.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Shared/_AutoCompletePartial.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Shared/_EnablePopoversPartial.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutColaborador.cshtml
  Codigo/GestaoGrupoMusicalWeb/wwwroot/js/autoComplete.js
  Codigo/GestaoGrupoMusicalWeb/wwwroot/js/enablePopovers.js
  Codigo/GestaoGrupoMusicalWeb/wwwroot/lib/jquery-autocomplete/code.jquery.com_ui_1.13.2_jquery-ui.js
  Codigo/GestaoGrupoMusicalWeb/wwwroot/lib/jquery-autocomplete/code.jquery.com_ui_1.13.2_themes_base_jquery-ui.css
  Codigo/Service/EnsaioService.cs
  Codigo/Service/PessoaService.cs
Labels: 6.0

#460 Implementado adição de colaboradores/regentes
  Codigo/Core/DTO/AssociadoDTO.cs
  Codigo/Core/Service/IGrupoMusicalService.cs
  Codigo/Core/Service/IPessoaService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/ColaboradorController.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/GrupoMusicalController.cs
  Codigo/GestaoGrupoMusicalWeb/Models/GrupoMusicalViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Colaborador/Create.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Colaborador/Delete.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/GrupoMusical/IndexAdmGrupo.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/GrupoMusical/_AddColaborador.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/GrupoMusical/_TabelaColaboradores.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutColaborador.cshtml
  Codigo/Service/EnsaioService.cs
  Codigo/Service/GrupoMusicalService.cs
  Codigo/Service/PessoaService.cs
Labels: enhancement, feat, 6.0

#464 Paginação da tela de movimentação figurino #454
  Codigo/GestaoGrupoMusicalWeb/Controllers/FigurinoController.cs
  Codigo/GestaoGrupoMusicalWeb/GestaoGrupoMusicalWeb.csproj
  Codigo/GestaoGrupoMusicalWeb/Views/Figurino/_TabelaMovimentacao.cshtml
Labels: 6.0

#474 Promover ROLE no Identity ao Adicionar Colaborador
  Codigo/Service/PessoaService.cs
Labels: enhancement, 6.0

#472 Adição de Funcionalidade para Editar Grupo Musical
  Codigo/Core/Service/IGrupoMusicalService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/AdministradorGrupoMusicalController.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/GrupoMusicalController.cs
  Codigo/GestaoGrupoMusicalWeb/Models/GrupoMusicalViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Views/GrupoMusical/IndexAdmGrupo.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/GrupoMusical/_EditAdmGrupo.cshtml
  Codigo/Service/GrupoMusicalService.cs
Labels: enhancement, 6.0

#471 Alterar retornos de inteiro por HttpStatusCode em UC - InstrumentoMusical
  Codigo/Core/Service/IInstrumentoMusicalService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/InstrumentoMusicalController.cs
  Codigo/Service/InstrumentoMusicalService.cs
Labels: refactor, 6.0
