Repository marcosdosea/GestaoGrupoMusical, pull requests merged in 2023-06, with the labels that each got.

#26 Email Campo Obrigatório UC - Manter Associados
  Codigo/GestaoGrupoMusicalWeb/Models/PessoaViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Create.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Details.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Edit.cshtml
Labels: enhancement, 1.0

#30 Implementação do UC Manter Ensaio
  AnaliseProjeto/GestaoGrupoMusical.mwb
  AnaliseProjeto/GestaoGrupoMusical.mwb.bak
  Codigo/Core/Service/IEnsaioService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/EnsaioController.cs
  Codigo/GestaoGrupoMusicalWeb/Mapper/EnsaioProfile.cs
  Codigo/GestaoGrupoMusicalWeb/Models/EnsaioViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Program.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/Create.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/Delete.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/Details.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/Edit.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/Index.cshtml
  Codigo/Service/EnsaioService.cs
Labels: 1.0

#40 Adicionar layout de perfil Colaborador
  Codigo/GestaoGrupoMusicalWeb/Views/Home/Index.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Shared/_Layout.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Shared/_Layout.cshtml.css
  Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutColaborador.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/_ViewStart.cshtml
  Codigo/GestaoGrupoMusicalWeb/wwwroot/css/site.css
  Codigo/GestaoGrupoMusicalWeb/wwwroot/lib/fontawesome-free-6.4.0-web/LICENSE.txt
  Codigo/GestaoGrupoMusicalWeb/wwwroot/lib/fontawesome-free-6.4.0-web/css/all.min.css
  Codigo/GestaoGrupoMusicalWeb/wwwroot/lib/fontawesome-free-6.4.0-web/webfonts/fa-brands-400.ttf
  Codigo/GestaoGrupoMusicalWeb/wwwroot/lib/fontawesome-free-6.4.0-web/webfonts/fa-brands-400.woff2
  Codigo/GestaoGrupoMusicalWeb/wwwroot/lib/fontawesome-free-6.4.0-web/webfonts/fa-regular-400.ttf
  Codigo/GestaoGrupoMusicalWeb/wwwroot/lib/fontawesome-free-6.4.0-web/webfonts/fa-regular-400.woff2
  Codigo/GestaoGrupoMusicalWeb/wwwroot/lib/fontawesome-free-6.4.0-web/webfonts/fa-solid-900.ttf
  Codigo/GestaoGrupoMusicalWeb/wwwroot/lib/fontawesome-free-6.4.0-web/webfonts/fa-solid-900.woff2
  Codigo/GestaoGrupoMusicalWeb/wwwroot/lib/simple-sidebar/LICENSE.txt
  Codigo/GestaoGrupoMusicalWeb/wwwroot/lib/simple-sidebar/dist/css/styles.css
  Codigo/GestaoGrupoMusicalWeb/wwwroot/lib/simple-sidebar/dist/js/scripts.js
Labels: 1.0

#41 Revisar testes para PessoaController e PessoaService.
  Codigo/GestaoGrupoMusicalWebTests/Controllers/PessoaControllerTests.cs
  Codigo/ServiceTests/PessoaServiceTests.cs
Labels: enhancement, 1.0

#46 Implementacão do testes de UC-Evento
  Codigo/GestaoGrupoMusicalWeb/Models/EventoViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Models/GrupoMusicalViewModel.cs
  Codigo/GestaoGrupoMusicalWebTests/Controllers/EventoControllerTests.cs
  Codigo/ServiceTests/EventoServiceTests.cs
Labels: enhancement, 1.0

#49 Adicionado Botão para Ver Administradores do Grupo Musical
  Codigo/GestaoGrupoMusicalWeb/Views/GrupoMusical/Index.cshtml
Labels: 1.0

#47 Implementado UC - Manter Administradores de Grupo Musical
  Codigo/Core/DTO/AdministradorGrupoMusicalDTO.cs
  Codigo/Core/Service/IPessoaService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/AdministradorGrupoMusicalController.cs
  Codigo/GestaoGrupoMusicalWeb/Mapper/AdministradorGrupoMusicalProfile.cs
  Codigo/GestaoGrupoMusicalWeb/Models/AdministradorGrupoMusicalViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Views/AdministradorGrupoMusical/Create.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/AdministradorGrupoMusical/Delete.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/AdministradorGrupoMusical/Index.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Create.cshtml
  Codigo/Service/PessoaService.cs
Labels: 1.0

#50 Teste de Unidade do UC - Manter Instrumento Musical
  Codigo/GestaoGrupoMusicalWebTests/Controllers/InstrumentoMusicalControllerTests.cs
  Codigo/ServiceTests/InstrumentoMusicalServiceTests.cs
Labels: 1.0

#62 UC - Manter Grupo Musical : Teste do método GetAllDTO
  Codigo/ServiceTests/GrupoMusicalServiceTests.cs
Labels: enhancement, 1.0

#65 Implementado GETALLDTO teste na Service/Evento
  Codigo/ServiceTests/EventoServiceTests.cs
Labels: 1.0

#67 Entrega e Devolução de Instrumento
  Codigo/Core/DTO/InstrumentoMusicalDTO.cs
  Codigo/Core/DTO/MovimentacaoInstrumentoDTO.cs
  Codigo/Core/Service/IInstrumentoMusicalService.cs
  Codigo/Core/Service/IMovimentacaoInstrumentoService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/InstrumentoMusicalController.cs
  Codigo/GestaoGrupoMusicalWeb/Models/MovimentacaoInstrumentoViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Program.cs
  Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/Index.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/Movimentar.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/_TabelaMovimentacao.cshtml
  Codigo/Service/InstrumentoMusicalService.cs
  Codigo/Service/MovimentacaoInstrumentoService.cs
Labels: 1.0

#68 Tradução dos textos da view: UC - Manter Associados
  Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/ChangeToCollaborator.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Create.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Delete.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Details.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Edit.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Index.cshtml
Labels: enhancement, 1.0

#78 Criado SelectList para os campos de pessoa em Criar pessoa.
  Codigo/GestaoGrupoMusicalWeb/Controllers/PessoaController.cs
  Codigo/GestaoGrupoMusicalWeb/Models/PessoaViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Program.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Create.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Edit.cshtml
Labels: enhancement, 1.0

#75 fix: Alterando PessoaViewModel.cs, colocando os campos required de acordo com o banco
  Codigo/GestaoGrupoMusicalWeb/Models/PessoaViewModel.cs
Labels: 1.0

#64 Traduções das Views de UC-Manter Evento
  Codigo/GestaoGrupoMusicalWeb/Controllers/EventoController.cs
  Codigo/GestaoGrupoMusicalWeb/Models/EventoViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Evento/Create.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Evento/Delete.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Evento/Details.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Evento/Edit.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Evento/Index.cshtml
  Codigo/GestaoGrupoMusicalWebTests/Controllers/EventoControllerTests.cs
Labels: enhancement, 1.0

#83 Adicionado campo de isento pagamento nas views de Pessoa/Associado.
  Codigo/GestaoGrupoMusicalWeb/Models/PessoaViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/ChangeToCollaborator.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Create.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Delete.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Details.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Edit.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Index.cshtml
Labels: enhancement, 1.0

#86 Notificações via e-mail de empréstimo e devolução de instrumentos e resolução de bugs
  Codigo/Core/DTO/MovimentacaoInstrumentoDTO.cs
  Codigo/Core/Service/IInstrumentoMusicalService.cs
  Codigo/Core/Service/IMovimentacaoInstrumentoService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/InstrumentoMusicalController.cs
  Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/_TabelaMovimentacao.cshtml
  Codigo/Service/InstrumentoMusicalService.cs
  Codigo/Service/MovimentacaoInstrumentoService.cs
Labels: 1.0

#89 Traduções da views de UC- Manter ensaio
  Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/Create.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/Delete.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/Details.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/Edit.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/Index.cshtml
Labels: 1.0, refactor

#85 Alterado botão e tag de view do UC - Manter ADM de Grupo Musical
  Codigo/GestaoGrupoMusicalWeb/Views/AdministradorGrupoMusical/Delete.cshtml
Labels: enhancement, 1.0

#91 Template de envio de email feito.
  Codigo/Email/Template/corpoEmailBatala.html
Labels: enhancement, 1.0

#93 Add tela 01 alta fidelidade
  Requisitos/Protótipos/Tela_01_Principal.png
Labels: 1.0

#100 Layout criado
  Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutColaborador.cshtml
  Codigo/GestaoGrupoMusicalWeb/wwwroot/css/headerLayout.css
Labels: enhancement, 1.5

#104 Add telas 01 e 07 alta fidelidade
  Requisitos/Protótipos/Tela_01_Principal.png
  Requisitos/Protótipos/Tela_07_Movimentar.png
Labels: documentation

#109 Adição do sufixo Service nas interfaces
  Codigo/Core/Service/IEventoService.cs
  Codigo/Core/Service/IGrupoMusicalService.cs
  Codigo/Core/Service/IManequimService.cs
  Codigo/Core/Service/IPapelGrupoService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/EnsaioController.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/EventoController.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/GrupoMusicalController.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/HomeController.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/PessoaController.cs
  Codigo/GestaoGrupoMusicalWeb/Program.cs
  Codigo/GestaoGrupoMusicalWebTests/Controllers/EventoControllerTests.cs
  Codigo/GestaoGrupoMusicalWebTests/Controllers/GrupoMusicalControllerTests.cs
  Codigo/GestaoGrupoMusicalWebTests/Controllers/PessoaControllerTests.cs
  Codigo/Service/EventoService.cs
  Codigo/Service/GrupoMusicalService.cs
  Codigo/Service/ManequimService.cs
  Codigo/Service/PapelGrupoService.cs
  Codigo/ServiceTests/EventoServiceTests.cs
  Codigo/ServiceTests/GrupoMusicalServiceTests.cs
  Codigo/ServiceTests/ManequimServiceTests.cs
Labels: refactor, 1.5

#106 Tradução de Views e SelectList - Instrumento Musical
  Codigo/Core/Service/IInstrumentoMusicalService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/InstrumentoMusicalController.cs
  Codigo/GestaoGrupoMusicalWeb/Models/InstrumentoMusicalViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/Create.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/Delete.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/Details.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/Edit.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/Index.cshtml
  Codigo/Service/InstrumentoMusicalService.cs
Labels: enhancement, 1.5

#117 Adicionado link para Associado no menu lateral
  Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutColaborador.cshtml
Labels: enhancement, 1.5

#118 Implementacao de seleclist no campo isento pagamento e ativo em pessoa
  Codigo/GestaoGrupoMusicalWeb/Controllers/PessoaController.cs
  Codigo/GestaoGrupoMusicalWeb/Models/PessoaViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Create.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Edit.cshtml
Labels: refactor, 1.5

#110 Corrigido bug ao adicionar administrador de um grupo que estava em outro
  Codigo/GestaoGrupoMusicalWeb/Controllers/AdministradorGrupoMusicalController.cs
  Codigo/Service/PessoaService.cs
Labels: bug, 1.5, Fix

#119 Ensaio Controller e Service tests
  Codigo/Core/Service/IEnsaioService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/EnsaioController.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/HomeController.cs
  Codigo/GestaoGrupoMusicalWeb/Models/PessoaViewModel.cs
  Codigo/GestaoGrupoMusicalWebTests/Controllers/EnsaioControllerTests.cs
  Codigo/GestaoGrupoMusicalWebTests/Controllers/GrupoMusicalControllerTests.cs
  Codigo/GestaoGrupoMusicalWebTests/Controllers/InstrumentoMusicalControllerTests.cs
  Codigo/GestaoGrupoMusicalWebTests/Controllers/PessoaControllerTests.cs
  Codigo/Service/EnsaioService.cs
  Codigo/ServiceTests/EnsaioServiceTests.cs
Labels: enhancement, test

#121 Adicionado Autenticação
  AnaliseProjeto/GestaoGrupoMusical.mwb
  Codigo/Core/Aspnetrole.cs
  Codigo/Core/Aspnetroleclaim.cs
  Codigo/Core/Aspnetuser.cs
  Codigo/Core/Aspnetuserclaim.cs
  Codigo/Core/Aspnetuserlogin.cs
  Codigo/Core/Aspnetusertoken.cs
  Codigo/Core/Core.csproj
  Codigo/Core/GrupoMusicalContext.cs
  Codigo/Core/Grupomusical.cs
  Codigo/Core/IdentityContext.cs
  Codigo/Core/Informativo.cs
  Codigo/Core/Instrumentomusical.cs
  Codigo/Core/Pessoa.cs
  Codigo/Core/UsuarioIdentity.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/IdentityController.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/InstrumentoMusicalController.cs
  Codigo/GestaoGrupoMusicalWeb/GestaoGrupoMusicalWeb.csproj
  Codigo/GestaoGrupoMusicalWeb/Models/IdentityViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Program.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Identity/Autenticar.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Identity/Cadastrar.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Identity/_ViewStart.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutColaborador.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutLogin.cshtml
Labels: 1.5

#123 Criação de PessoaDTO e uso da mesma na view Index
  Codigo/Core/DTO/AssociadoDTO.cs
  Codigo/Core/Service/IPessoaService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/PessoaController.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Index.cshtml
  Codigo/Service/PessoaService.cs
Labels: enhancement, 1.5

#124 Mudança de selectlist para PessoaService
  Codigo/Core/Service/IPessoaService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/PessoaController.cs
  Codigo/Service/PessoaService.cs
Labels: enhancement, 1.5

#127 Ids retirados de instrumento musical
  Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/Create.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/Edit.cshtml
Labels: refactor, 1.5

#140 refactor: alteracao na rotas da aplicacao, indo direto para home.
  Codigo/GestaoGrupoMusicalWeb/Program.cs
Labels: refactor, 1.5

#132 Refatoração dao UC - Manter Colaborador
  Codigo/Core/Service/IPessoaService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/ColaboradorController.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/PessoaController.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Colaborador/Create.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Colaborador/Delete.cshtml
  Codigo/Service/PessoaService.cs
Labels: 1.5

#143 Refatorando a classe pessoaViewModel
  Codigo/GestaoGrupoMusicalWeb/Controllers/PessoaController.cs
  Codigo/GestaoGrupoMusicalWeb/Models/PessoaViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Create.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Edit.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutColaborador.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutLogin.cshtml
  Codigo/GestaoGrupoMusicalWeb/wwwroot/lib/jquery-mask/jquery.inputmask.js
Labels: refactor, 1.5, feat

#149 Campos de erro adicionados e StringLength
  Codigo/GestaoGrupoMusicalWeb/Models/InstrumentoMusicalViewModel.cs
Labels: bug, 1.5

#142 Implementação do css da Home/index
  Codigo/GestaoGrupoMusicalWeb/Views/Home/Index.cshtml
Labels: enhancement, 1.5

#146 Adicionado estilo aos inputs
  Codigo/GestaoGrupoMusicalWeb/wwwroot/css/site.css
  Codigo/GestaoGrupoMusicalWeb/wwwroot/icon/checkbox_icon.svg
  Codigo/GestaoGrupoMusicalWeb/wwwroot/icon/invalid_icon.svg
  Codigo/GestaoGrupoMusicalWeb/wwwroot/icon/radio_icon.svg
  Codigo/GestaoGrupoMusicalWeb/wwwroot/icon/select_icon.svg
Labels: 1.5

#136 SelectList para status implementado
  Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/Create.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/InstrumentoMusical/Edit.cshtml
Labels: enhancement, 1.5

#150 Adicionando mascara em campo cpf de autenticar e cadastrar
  Codigo/GestaoGrupoMusicalWeb/Controllers/IdentityController.cs
  Codigo/GestaoGrupoMusicalWeb/Models/IdentityViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Models/PessoaViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Identity/Autenticar.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Identity/Cadastrar.cshtml
Labels: 1.5, feat
