Repository marcosdosea/GestaoGrupoMusical, pull requests merged in 2024-08, with the labels that each got.

#625 Implementado a funcionalidade do service de Edit Evento
  Codigo/Core/Service/IEventoService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/EventoController.cs
  Codigo/Service/EventoService.cs
Labels: enhancement

#628 Implementar delete de Ensaios
  Codigo/Core/Service/IEnsaioService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/EnsaioController.cs
  Codigo/Service/EnsaioService.cs
Labels: Fix

#633 Implementar Registro de Frequencia
  Codigo/Core/DTO/AssociadoDTO.cs
  Codigo/Core/Service/IPessoaService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/EnsaioController.cs
  Codigo/GestaoGrupoMusicalWeb/Models/EnsaioViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/RegistrarFrequencia.cshtml
  Codigo/Service/PessoaService.cs
Labels: Fix

#640 Fix - removido erro de compilacao
  Codigo/Core/Service/IEventoService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/EventoController.cs
Labels: Fix

#635 Implementando a index de Informativo
  Codigo/Core/Service/IInformativoService.cs
  Codigo/Core/Service/IMaterialEstudoService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/InformativoController.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/MaterialEstudoController.cs
  Codigo/Service/InformativoService.cs
  Codigo/Service/MaterialEstudoService.cs
Labels: Fix

#647 Implementar REgistro de Frequencia em Ensaio
  Codigo/Core/DTO/AssociadoDTO.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/EnsaioController.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/RegistrarFrequencia.cshtml
Labels: Fix

#646 Branch implementar solicitacao evento 642
  Codigo/Core/DTO/EventoDTO.cs
  Codigo/Core/Service/IEventoService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/EventoController.cs
  Codigo/GestaoGrupoMusicalWeb/Mapper/EventoProfile.cs
  Codigo/GestaoGrupoMusicalWeb/Models/EventoViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Evento/GerenciarSolicitacaoEvento.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Evento/Index.cshtml
  Codigo/Service/EventoService.cs
Labels: enhancement

#643 Finalizado implementacao da index de informativo
  Codigo/Core/DTO/InformativoDTO.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/InformativoController.cs
  Codigo/GestaoGrupoMusicalWeb/Mapper/InformativoProfile.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Informativo/Index.cshtml
  Codigo/Service/InformativoService.cs
Labels: enhancement

#660 Agora os dados dos associados ativos aparecem!
  Codigo/Core/Service/IPessoaService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/EnsaioController.cs
  Codigo/GestaoGrupoMusicalWeb/Models/EnsaioViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/RegistrarFrequencia.cshtml
  Codigo/Service/PessoaService.cs
Labels: feat

#662 Fix rota de RegistrarFrequencia
  Codigo/GestaoGrupoMusicalWeb/Controllers/EnsaioController.cs
Labels: Fix

#659 Implementar Dump de Grupo Musical
  AnaliseProjeto/v_dump_grupo_musical_referente_MD.md
  AnaliseProjeto/v_dump_grupo_musical_referente_MD.sql
Labels: enhancement

#651 Montando a view e pegando os dados.
  Codigo/Core/DTO/EventoDTO.cs
  Codigo/Core/Service/IEventoService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/EventoController.cs
  Codigo/GestaoGrupoMusicalWeb/Models/EventoViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Evento/GerenciarSolicitacaoEvento.cshtml
  Codigo/Service/EventoService.cs
Labels: feat

#670 Adicionado o sln
  Codigo/GestaoGrupoMusical.sln
Labels: enhancement

#668 Branch finalizar solicitacao grupo musical 664
  AnaliseProjeto/v_dump_grupo_musical_referente_MD.sql
  Codigo/Core/DTO/EventoDTO.cs
  Codigo/Core/Service/IEventoService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/EventoController.cs
  Codigo/GestaoGrupoMusicalWeb/Models/EventoViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Evento/GerenciarSolicitacaoEvento.cshtml
  Codigo/GestaoGrupoMusicalWeb/appsettings.json
  Codigo/Service/EventoService.cs
Labels: feat

#675 Fix - finalizado index de evento
  Codigo/GestaoGrupoMusicalWeb/Views/Evento/Index.cshtml
  Codigo/Service/EventoService.cs
Labels: Fix
