Repository marcosdosea/GestaoGrupoMusical, pull requests merged in 2024-06, with the labels that each got.

#541 Adicionado view de index.
  Codigo/Core/Core.csproj
  Codigo/Core/DTO/MaterialEstudoIndexDTO.cs
  Codigo/Core/Service/IMaterialEstudoService.cs
  Codigo/Core/Service/MaterialEstudoDTO.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/MaterialEstudoController.cs
  Codigo/GestaoGrupoMusicalWeb/GestaoGrupoMusicalWeb.csproj
  Codigo/GestaoGrupoMusicalWeb/Mapper/MaterialEstudoProfileIndexDTO.cs
  Codigo/GestaoGrupoMusicalWeb/Models/MaterialEstudoViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Models/MaterialEstudoViewModelDTO.cs
  Codigo/GestaoGrupoMusicalWeb/Views/MaterialEstudo/Index.cshtml
  Codigo/Service/MaterialEstudoService.cs
Labels: enhancement

#547 Branch vere material estudo delete 543
  Codigo/GestaoGrupoMusicalWeb/Controllers/MaterialEstudoController.cs
  Codigo/Service/MaterialEstudoService.cs
Labels: enhancement, 2.0

#555 Implementação material estudo service tests
  Codigo/ServiceTests/MaterialEstudoServiceTests.cs
Labels: enhancement

#554 552 implementar material de estudo edit
  Codigo/Core/Core.csproj
  Codigo/Core/DTO/MaterialEstudoIndexDTO.cs
  Codigo/Core/Service/IMaterialEstudoService.cs
  Codigo/Core/Service/MaterialEstudoDTO.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/MaterialEstudoController.cs
  Codigo/GestaoGrupoMusicalWeb/GestaoGrupoMusicalWeb.csproj
  Codigo/GestaoGrupoMusicalWeb/Mapper/MaterialEstudoProfile.cs
  Codigo/GestaoGrupoMusicalWeb/Mapper/MaterialEstudoProfileIndexDTO.cs
  Codigo/GestaoGrupoMusicalWeb/Models/MaterialEstudoViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Models/MaterialEstudoViewModelDTO.cs
  Codigo/GestaoGrupoMusicalWeb/Program.cs
  Codigo/GestaoGrupoMusicalWeb/Views/MaterialEstudo/Edit.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/MaterialEstudo/Index.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutColaborador.cshtml
  Codigo/Service/MaterialEstudoService.cs
Labels: 2.0

#553 Notificação de Material Estudo foi finalizada 544
  Codigo/Core/DTO/PessoaEnviarEmailDTO.cs
  Codigo/Core/Service/IGrupoMusicalService.cs
  Codigo/Core/Service/IMaterialEstudoService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/MaterialEstudoController.cs
  Codigo/GestaoGrupoMusicalWeb/Views/MaterialEstudo/Index.cshtml
  Codigo/Service/GrupoMusicalService.cs
  Codigo/Service/MaterialEstudoService.cs
Labels: enhancement, 5.0

#557 552 implementar material de estudo edit
  Codigo/GestaoGrupoMusicalWeb/Controllers/MaterialEstudoController.cs
  Codigo/GestaoGrupoMusicalWeb/Views/MaterialEstudo/Edit.cshtml
Labels: enhancement

#556 Implementar Material Estudo#542
  Codigo/Core/Service/IMaterialEstudoService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/InstrumentoMusicalController.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/MaterialEstudoController.cs
  Codigo/GestaoGrupoMusicalWeb/Views/MaterialEstudo/Create.cshtml
  Codigo/Service/MaterialEstudoService.cs
  Requisitos/Casos de Uso Usuário.docx
Labels: enhancement

#560 552 implementar material de estudo edit
  Codigo/Core/DTO/PessoaEnviarEmailDTO.cs
  Codigo/Core/Service/IGrupoMusicalService.cs
  Codigo/Core/Service/IMaterialEstudoService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/InstrumentoMusicalController.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/MaterialEstudoController.cs
  Codigo/GestaoGrupoMusicalWeb/Views/MaterialEstudo/Create.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/MaterialEstudo/Edit.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/MaterialEstudo/Index.cshtml
  Codigo/Service/GrupoMusicalService.cs
  Codigo/Service/MaterialEstudoService.cs
  Codigo/ServiceTests/MaterialEstudoServiceTests.cs
  Requisitos/Casos de Uso Usuário.docx
Labels: enhancement

#564 Notificacao de Evento adicionada
  Codigo/Core/Service/IEventoService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/EventoController.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Evento/Index.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutColaborador.cshtml
  Codigo/Service/EventoService.cs
Labels: enhancement

#562 Branch vere alteracao nas view banco material estudo 561
  AnaliseProjeto/GestaoGrupoMusical.mwb
  AnaliseProjeto/GestaoGrupoMusical.mwb.bak
  Codigo/Core/GrupoMusicalContext.cs
  Codigo/GestaoGrupoMusicalWeb/Views/MaterialEstudo/Create.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/MaterialEstudo/Edit.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/MaterialEstudo/Index.cshtml
  Codigo/Service/MaterialEstudoService.cs
Labels: Fix

#566 Padronizado o layout de index de eventos para futuras edições.
  Codigo/Core/DTO/EventoIndexDTO.cs
  Codigo/Core/Service/IEventoService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/EventoController.cs
  Codigo/GestaoGrupoMusicalWeb/Models/EventoViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Evento/Index.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/MaterialEstudo/Index.cshtml
  Codigo/Service/EventoService.cs
Labels: Fix

#572 Exibindo no menu lateral esquerdo a opção Informativos.
  Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutColaborador.cshtml
Labels: enhancement

#574 Feito as alterações solicitadas na reunião.
  Codigo/Core/DTO/MaterialEstudoDTO.cs
  Codigo/Core/Service/IMaterialEstudoService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/MaterialEstudoController.cs
  Codigo/GestaoGrupoMusicalWeb/Mapper/MaterialEstudoProfile.cs
  Codigo/GestaoGrupoMusicalWeb/Views/MaterialEstudo/Edit.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/MaterialEstudo/Index.cshtml
  Codigo/Service/MaterialEstudoService.cs
Labels: Fix

#577 Atualizar_Protótipo_Informativo#576
  Requisitos/Protótipos/tela25informativo_edit.png
  Requisitos/Protótipos/tela26informativo_add.png
Labels: Fix

#578 Página "Create" de Informativo
  AnaliseProjeto/GestaoGrupoMusical.mwb
  AnaliseProjeto/GestaoGrupoMusical.mwb.bak
  Codigo/GestaoGrupoMusicalWeb/Controllers/InformativoController.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Informativo/Create.cshtml
Labels: enhancement

#581 Fix - Controller e rotas na view index de Informativo
  Codigo/GestaoGrupoMusicalWeb/Controllers/InformativoController.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Informativo/Index.cshtml
Labels: Fix
