Repository marcosdosea/GestaoGrupoMusical, pull requests merged in 2024-09, with the labels that each got.

#680 677 - Implementar instrumento planejado evento
  Codigo/Core/DTO/EventoDTO.cs
  Codigo/Core/DTO/FigurinoDTO.cs
  Codigo/Core/GrupoMusicalContext.cs
  Codigo/Core/Service/IEventoService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/EventoController.cs
  Codigo/GestaoGrupoMusicalWeb/Models/EventoViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Evento/GerenciarInstrumentoEvento.cshtml
  Codigo/Service/EventoService.cs
  Codigo/Service/Service.csproj
Labels: feat

#684 Implementada as funcionalidades
  Codigo/Core/DTO/AssociadoEventoDTO.cs
  Codigo/Core/Service/IEventoService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/EventoController.cs
  Codigo/GestaoGrupoMusicalWeb/Models/EventoJustificativaViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Models/EventoViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Evento/Index.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Evento/RegistrarFrequencia.cshtml
  Codigo/Service/EventoService.cs
Labels: enhancement

#696 687 implementar novo pagamento
  Codigo/Core/DTO/FinanceiroDTO.cs
  Codigo/Core/Service/IFinanceiroService.cs
  Codigo/Core/Service/IPessoaService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/FinanceiroController.cs
  Codigo/GestaoGrupoMusicalWeb/Mapper/FinanceiroProfile.cs
  Codigo/GestaoGrupoMusicalWeb/Models/FinanceiroCreateViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Evento/GerenciarSolicitacaoEvento.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Financeiro/Create.cshtml
  Codigo/Service/FinanceiroService.cs
  Codigo/Service/PessoaService.cs
Labels: feat

#702 689 implementar visualização de instrumentos planejados evento
  Codigo/Core/DTO/GerenciarInstrumentoEventoDTO.cs
  Codigo/Core/DTO/InstrumentoPlanejadoEventoDTO.cs
  Codigo/Core/Service/IEventoService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/EventoController.cs
  Codigo/GestaoGrupoMusicalWeb/Models/EventoViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Evento/_TabelaGerenciarInstrumento.cshtml
  Codigo/Service/EventoService.cs
Labels: Fix

#701 700 fix ao adicionar tabelas ja inserir associados dentro
  AnaliseProjeto/v_dump_grupo_musical_referente_MD.md
  AnaliseProjeto/v_dump_grupo_musical_referente_MD.sql
  Codigo/Core/Service/IEnsaioService.cs
  Codigo/Core/Service/IPessoaService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/EnsaioController.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/EventoController.cs
  Codigo/GestaoGrupoMusicalWeb/Models/EnsaioViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/Edit.cshtml
  Codigo/Service/EnsaioService.cs
  Codigo/Service/PessoaService.cs
Labels: Fix

#704 703 implementar evento associado
  Codigo/Core/DTO/AssociadoEventoDTO.cs
  Codigo/Core/DTO/EnsaioAssociadoDTO.cs
  Codigo/Core/DTO/EnsaioDTO.cs
  Codigo/Core/DTO/EventoDTO.cs
  Codigo/Core/Service/IEnsaioService.cs
  Codigo/Core/Service/IEventoService.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/EnsaioController.cs
  Codigo/GestaoGrupoMusicalWeb/Controllers/EventoController.cs
  Codigo/GestaoGrupoMusicalWeb/Mapper/EventoProfile.cs
  Codigo/GestaoGrupoMusicalWeb/Models/EnsaioViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Models/EnsaioViewModelDTO.cs
  Codigo/GestaoGrupoMusicalWeb/Models/EventoViewModel.cs
  Codigo/GestaoGrupoMusicalWeb/Views/Ensaio/EnsaiosAssociado.cshtml
  Codigo/GestaoGrupoMusicalWeb/Views/Shared/_LayoutAssociado.cshtml
  Codigo/GestaoGrupoMusicalWeb/appsettings.json
  Codigo/Service/EnsaioService.cs
  Codigo/Service/EventoService.cs
Labels: enhancement
